# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  J1_Joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: -1.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 20.0
  J2_Joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: -1.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 20.0
  J3_Joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: -1.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 20.0
  J4_Joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: -1.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 20.0
  J5_Joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: -1.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 20.0
  J6_Joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: -1.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 20.0